databases:
  - name: spypizza-db
    plan: free

services:
  - type: web
    name: spypizza
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn pizza.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        fromDatabase:
          name: spypizza-db
          property: connectionString
