# Generated by Django 4.2.20 on 2025-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'food',
            },
        ),
    ]
