# Generated by Django 4.2.20 on 2025-04-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='information',
        ),
    ]
