# Generated by Django 4.2.20 on 2025-04-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='food',
        ),
    ]
