# Generated by Django 4.2.20 on 2025-04-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_cart_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
